### ISSUE TITLE
Error: I can't run this version..

### ISSUE THREAD

**Issue by psam25** [LevPasha/Instagram-API-python#1]
Error code:

```
Traceback (most recent call last):
  File "..........py", line 488, in <module>
    InstagramAPI.login() # login
  File "..........py", line 64, in login
    if (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)):
  File "..........py", line 437, in generateSignature
return 'ig_sig_key_version=' + self.SIG_KEY_VERSION + '&signed_body=' + hmac.new(self.IG_SIG_KEY.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).hexdigest() + '.' + urllib.parse.quote(data)
AttributeError: 'module' object has no attribute 'parse'
```

**Comment by LevPasha** [comment]
@psam25 Show all your code. I don't test all functions, test only that list in example.

**Comment by psam25** [comment]
I use your code without changes, I tried to get it working.

**Comment by psam25** [comment]
Btw change your password!! (see source code..)

**Comment by LevPasha** [comment]
@psam25 hard day... what is your python version?

**Comment by psam25** [comment]
Gehe oke, 3.0

**Comment by LevPasha** [comment]
@psam25 i use 3.4.3 and test all on this version. Try to update...

**Comment by psam25** [comment]
Ah oke, I use normally python 2.7. I hate the new python 3.x coding..

**Comment by LevPasha** [comment]
@psam25 sorry i can't satisfy everyone.

**Comment by psam25** [comment]
Ah one doesn't matter, I installed python 3.4 and it seems to work.
`Login success!`

Thanks

**Comment by LevPasha** [comment]
@psam25 this is't bot, this is just api. Config and use it yourself.

**Comment by cmagorian** [comment]
I have the same issue, what was the solution to this @psam25

**Comment by cmagorian** [comment]
running python 3.5

**Comment by dsouzarc** [comment]
I've been commenting this everywhere, but I believe I fixed the issues in [this Pull Request](https://github.com/LevPasha/Instagram-API-python/pull/71). 

Basically, it's because the `urllib` was split into more modules (like `urllib.parse`) from Python 2 to Python 3, so depending on version you're running, you might run into issues. 

If it hasn't been merged yet, try cloning and running it from my repo: [https://github.com/dsouzarc/Instagram-API-python] (https://github.com/dsouzarc/Instagram-API-python)
