### ISSUE TITLE
Error in account creation after 10th April update

### ISSUE THREAD

**Issue by fragiledream** [LevPasha/Instagram-API-python#150]
It seems that after the 10th April update, the registration won't work. It always throws HTTP Error 400 with a response message containing "spam":"true". However, manual registration from browser or mobile works so it's not a IP thing.

**Comment by ThomasMW** [comment]
Instagrams API changed, so you need to update your code to use the correct endpoints.

**Comment by h-2-0** [comment]
Hi @fragiledream 

I read your other post in the issues section of the Instagram API PHP github. Did you port their registration PHP code into Python? If so, could you share the Python code here? Otherwise, I'd love if you could share me the PHP code one as well (not for abuse but understanding the registration process). Thanks!
