### ISSUE TITLE
Direct Share

### ISSUE THREAD

**Issue by chiragshah1312** [LevPasha/Instagram-API-python#218]
Can someone please help with a proper syntax for direct share in case if it works.
I have tried this but it says : 
{'message': 'Thread does not exist', 'status': 'fail'}

```
InstagramAPI.tagFeed('cute')
tag_media = InstagramAPI.LastJson
mediaId= str(tag_media['items'][0]['id']) 
recipients = [259904706]                      
InstagramAPI.direct_share(mediaId, recipients,text='aquest es es darrer')
```

**Comment by chiragshah1312** [comment]
@xecgr can you help us with this issue please!

**Comment by xecgr** [comment]
Hi @chiragshah1312 , could you please test this minor change:
InstagramAPI.py:241
```
{
    'type' : 'form-data',
    'name' : 'thread', #'thread_ids', #it seems it changed its property name
    'data' : '["0"]',
},
```

If it works, I'll create a pull request with this fix

**Comment by chiragshah1312** [comment]
Hello,
Your magic has put it back to work again. Amazing job thanks a lot for your
time. Can you tell me how did you find that the name was changed? Do you
have access to instagram private apis or you have used fiddler?

**Comment by xecgr** [comment]
I'm checked the [php project](https://github.com/mgp25/Instagram-API), which is actively mantained.
Its code is more complex, but it queries the same api endpoints. So, in this case, I've checked php's direct_share feature and I've compared sent params.
During this days, I'll create a pull request with this fix, so in the near future this issue will be fixed in master branch
