### ISSUE TITLE
Bot doesnt follow

### ISSUE THREAD

**Issue by 179skr** [LevPasha/Instagram-API-python#25]
I am running the code on my server as a test.py but it doesnt seem to work. I am a noob and i am still learning coding. Is it the code ive done or is it the bot.  My code is below

InstagramAPI = InstagramAPI("login", "password")
InstagramAPI.login() # login```
InstagramAPI.getUserFollowers("111111", next_max_id)
temp = InstagramAPI.LastJson
temp['users'][0] # this gets the latest 
for f in temp:
      Bot.follow('users_id')

**Comment by ahmdrz** [comment]
Hi , 
getUserFollowers need two arguments , usernameID and next_max_id

usernameId is a string which is a code, for each user you want to get followers , you have to send usernameId of that user to this argument , so `11111`` is incorrect.

And next_max_id , getUserFollowers work like a pagination , for each time you call this method , the next_max_id will change .

See [this](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L566)

for the firsttime you can use `InstagramAPI.getUserFollowers(usernameId)` , because the second argument is filled by a default value.

And I don't know about `Bot.follow('users_id')` , what is Bot and where was it defined ?

> Sorry for my english 
> Best regards

**Comment by ahmdrz** [comment]
Hi , 
getUserFollowers need two arguments , usernameID and next_max_id

usernameId is a string which is a code, for each user you want to get followers , you have to send usernameId of that user to this argument , so `11111`` is incorrect.

And next_max_id , getUserFollowers work like a pagination , for each time you call this method , the next_max_id will change .

See [this](https://github.com/LevPasha/Instagram-API-python/blob/master/InstagramAPI.py#L566)

for the firsttime you can use `InstagramAPI.getUserFollowers(usernameId)` , because the second argument is filled by a default value.

And I don't know about `Bot.follow('users_id')` , what is Bot and where was it defined ?

> Sorry for my english 
> Best regards

**Comment by 179skr** [comment]
@ahmdrz could you show me a full working example?

And it should be InstagramAPI.follow

**Comment by ahmdrz** [comment]
@179skr  Please check #22
