### ISSUE TITLE
Verification Loop "Request return 400 error!"

### ISSUE THREAD

**Issue by anthonysette** [LevPasha/Instagram-API-python#283]
I try to log in via the API but every time I get "Request return 400 error!". Then I go to my device and verify that "This was me", go back to log in and get the same message... This cycle repeats over and over and apparently, this is a new problem. They call it the verification loop, anyone else have this experience? Anyone have a fix?

**Comment by jockonarock** [comment]
Hi I am working on a fix regarding this issue but can't seem to replicate the issue myself. If you are willing to collaborate with me, let me know

**Comment by anthonysette** [comment]
I am absolutely willing to work with you, and there is something I did notice. What version of python are you running? When I use python 3.x I fall into this loop but when I use python 2.x there seems to be no issues and I can log into any account.

**Comment by joselitinho1** [comment]
@anthonysette using the same api and IP?
are you trying from home or hosting?

**Comment by jockonarock** [comment]
@anthonysette could you add me on Facebook? Look for Cosmos Williams. Galaxy profile picture

**Comment by LevPasha** [comment]
The problem is different ip - where you login and confirm.

**Comment by Haydardi** [comment]
@LevPasha  Does that mean that proxies does not work anymore? Meaning if I'm using proxies from different countries and make the verification from my local IP. Or is there a way to verify automatically, through the API?

**Comment by Perados** [comment]
@LevPasha I am having the same problem here. It is not only IP address related, I think it is also related to the User Agent, or a combination of IP and User Agent, and probably other factors. I can login from the browser, but I get the 400 using this library, then get the /challenge page again in the browser, and I can repeat the whole process, over and over again.

**Comment by jockonarock** [comment]
It seems that this still works for accounts that were previously using this API. However, personally I get the verification loop whenever I try to login via API with new accounts.

Yes I agree that it should be a combination of proxy and useragent that is causing the problem. 

Can someone explain what role does sig key play? I am quite new to this. Thanks in advance.

**Comment by Perados** [comment]
Mine started working again last night. Probably Instagram changed something on their side. Weird, but at least it works now. 👍

**Comment by jockonarock** [comment]
@perados same here. Not sure if this issue would come back though. Hopefully not!

**Comment by Haydardi** [comment]
Mine stopped working! I've changed android version,  sig key, proxy etc and it worked with 1 account and did not with 4 others.

Keeps getting this annoying verification loop. Damn you Instagram!

**Comment by jockonarock** [comment]
@Haydardi I run into the verification loop whenever I try to use accounts that have not been connected to the bot before. But existing accounts seem to be okay

**Comment by Perados** [comment]
My bots stopped working again. Instagram's security guys are doing a good job, sadly for us.

My idea would be to generate a new sig key, one that would be linked to my iPhone's user agent and use my home's ip address as a proxy for my bots (they live on EC2). This way, I guess Instagram wouldn't be able to make a difference between my bots and my phone, because I can login to all my accounts from my phone at home.
Anyway, I need time to do this, and I don't even know if getting the sig key from Instagram on an iPhone is possible. Anyone that would like to help?

**Comment by Haydardi** [comment]
@jockonarock Yeah same happens to me as well. But the main interest is adding new accounts to the bot and not just old ones. However, no matter what we need to figure out how to crack this thing! I'm ready to go all in on this one! 

You guys think it has something to do with proxy location in reference to user's main location or proxy in general?

**Comment by Haydardi** [comment]
I might have a clue, who in here have cracked the sig key for the latest Instagram APK (
Instagram 31.0.0.0.6 (88952) ) or knows how to do it?

**Comment by joselitinho1** [comment]
I had. Let you email.

**Comment by jockonarock** [comment]
Hey cc me in the conversation. I want to help too.

@haydardi @joselitinho1

But at the moment I don't think the problem is with the Sig key... If I were working for instagram, what would raise suspicion would be logins from new location (IP) with different device setting. Because I have been travelling lately and I don't get any verification loop on my phone when I sign in from a new IP on the same device.

Thoughts?

**Comment by Perados** [comment]
They check the ip address **and** sig key imho. The sig key is linked to your user agent, so for sure they check both. This library uses a very old user agent, hence a very old sig key. I think they find it fishy that usually I login from my iPhone on the newest version of Instagram from France, but from time to time I login from an old Xiaomi on a super old version of Instagram from the US.
If we can find a way to get our real sig key (and user agent) every time, then we win. The ip address is easier to mock.

Could anyone who already cracked sig keys contact me, please? Android or iOS, I'll take both, and share my results.

**Comment by Haydardi** [comment]
@joselitinho1 you have the latest sig keys? Can you share them please?

Also, is there a difference between Android or iOS sig keys? I don't think so as its the application key.

@jockonarock I use proxies and some of my accounts do get successfully out of the challenge loop. This may be because each time I re-login to the bot I assign another user agent with different sig key and Instagram app version, chosen by random. However, this only works on accounts (4 out of 10 accounts) that are either on Android only and/or not updated their Instagram to the latest version. I don't know for sure yet.

I want to see if the sig key for the latest Instagram app release make a difference for the accounts that have updated to the latest version.

**Comment by Perados** [comment]
I don't have time to try this right now, but this repo has a more recent sig key : https://github.com/mgp25/Instagram-API/blob/master/src/Constants.php

You guys can try using that sig key in this project and let me know if it works. I am still looking for a way to get the newest sig keys.

**Comment by Haydardi** [comment]
@Perados I'm already using it. However it is not the latest. Still looking for a way to retrieve latest sig keys. Did you get any luck?

**Comment by LevPasha** [comment]
Check my answer https://github.com/LevPasha/Instagram-API-python/issues/283#issuecomment-357773457

**Comment by DjarDjar** [comment]
yo did you guys found a solution? I tried everything and for my 3 ig accounts it didn't work. So?
