### ISSUE TITLE
How to get user followers to a specified number instead of dumping everything ??

### ISSUE THREAD

**Issue by Sacheth98** [LevPasha/Instagram-API-python#552]

**Comment by Chadhendrixs** [comment]
This is not the place for that, that question would be more appropriate on stackoverflow due to it's nature. This is for bugs with the code, not not knowing how to process the data.

But, since we're here, treat the request as JSON data using the JSON module. Navigate to 'items' in the dictionary 'aymf'. Use the code found [here](https://github.com/LevPasha/Instagram-API-python/blob/master/examples/user_followings.py) and modify it to work with current versions as well as your version of python. Good luck.

**Comment by Sacheth98** [comment]
Sure thanks
