### ISSUE TITLE
API.follow(int) and API.follow(str) both return True despite failed action

### ISSUE THREAD

**Issue by phbprogramming** [LevPasha/Instagram-API-python#574]
When trying to follow an account given it's "pk" the function completes without error, but the follow is not reflected within the native application, or when retrieving my own follow list. It appears follow() is no longer working for me. Could this be my account, or the library? I am currently following 900 people.

**Comment by ChrisBuetti** [comment]
It's because you're getting denied.

If you were to use Instagram via the app on your phone, and you followed a lot of people in a short amount of time, it would stop you. What would happen is you would click the blue "follow" button, it would turn grey and say "followed" for a split second, and then go back to the blue "follow" button. The same thing is happening via the api. Unfortunately, the API is not smart enough to realize it wasn't successful right away, it takes some time.

I rectify this by only following public accounts (no request accept needed) and compare my following account before and after. If it has increased by 1, it worked. If not, fail, and I sleep for a while.

**Comment by phbprogramming** [comment]
Many thanks.
