### ISSUE TITLE
PyMySQL? pymongo? numpy? matplotlib?? Kivy? Jinja2? Flask? docker? 

### ISSUE THREAD

**Issue by k1-hedayati** [LevPasha/Instagram-API-python#79]
`requirements.txt` of project is dump of your whole system packages? Or you're using both MySQL and MongoDB for an API library? I appropriate your affords but this repo needs lots of improvments

**Comment by h-2-0** [comment]
@k1-hedayati 

I've been using this Instagram API for sometime without even realising there was a requirements text file! Oh, well...I think you should disregard it.

And as for improvements that's why you, others and me are here for. That is, to contribute toward LevPasha's repo. He already did us a big favour porting most of Instagram-API (PHP) from mgp25.
