### ISSUE TITLE
uploadPhoto

### ISSUE THREAD

**Issue by virux84** [LevPasha/Instagram-API-python#96]
Hi, 
when I try to run this code for upload a photo, I always get "Request return 400 error!"
What I am doing wrong?

`from InstagramAPI import InstagramAPI
InstagramAPI = InstagramAPI("user", "pass")
InstagramAPI.login()
InstagramAPI.uploadPhoto('wom.jpg')`

This request returns:

> {u'status': u'fail', u'message': u"Uploaded image isn't in the right format"}

Thank you

**Comment by conorosully** [comment]
Did you solve this? I have a similar problem...

**Comment by conorosully** [comment]
I found that the problem is with imghdr.what() function in the ImageUtils.py file. The function has difficulty identifying some JPEG images. As I am 100% sure that I am only going to be uploading JPEGs, I just changed the logical statements in the getImageSize() function so that it always thinks the image is a JPEG.

**Comment by mehrdadmms** [comment]
@conorosully 

Hi 
I'm uploading PNG files but I have the same problem 
Although I think i can limit my photos to JPEG

Can I see you're getImageSize() function ? 

thank you
